export const cityData = [
    {
      text: "昆明市",
      value: "kunming",
      children: [
        { text: "五华区", value: "wuhua" },
        { text: "盘龙区", value: "panlong" },
        { text: "官渡区", value: "guandu" },
        { text: "西山区", value: "xishan" },
        { text: "东川区", value: "dongchuan" },
        { text: "呈贡区", value: "chenggong" },
        { text: "晋宁县", value: "jinning" },
        { text: "富民县", value: "fumin" },
        { text: "宜良县", value: "yiliang" },
        { text: "石林彝族自治县", value: "shilinyizuzizhixian" },
        { text: "嵩明县", value: "songming" },
        { text: "禄劝彝族苗族自治县", value: "luquanyizumiaozuzizhixian" },
        { text: "寻甸回族彝族自治县", value: "xundienuizuyizuzizhixian" },
        { text: "安宁市", value: "anning" },
      ],
    },
    {
      text: "曲靖市",
      value: "qujing",
      children: [
        { text: "麒麟区", value: "qilin" },
        { text: "沾益区", value: "zhanyi" },
        { text: "马龙区", value: "malong" },
        { text: "陆良县", value: "lu-liang" },
        { text: "师宗县", value: "shizong" },
        { text: "罗平县", value: "luoping" },
        { text: "富源县", value: "fuyuan" },
        { text: "会泽县", value: "huize" },
        { text: "宣威市", value: "xuanwei" },
      ],
    },
    {
      text: "玉溪市",
      value: "yuxi",
      children: [
        { text: "红塔区", value: "hongta" },
        { text: "江川区", value: "jiangchuan" },
        { text: "澄江县", value: "chengjiang" },
        { text: "通海县", value: "tonghai" },
        { text: "华宁县", value: "huaning" },
        { text: "易门县", value: "yimen" },
        { text: "峨山彝族自治县", value: "eshanyizuzizhixian" },
        { text: "新平彝族傣族自治县", value: "xinpingyizu-daizuzizhixian" },
        { text: "元江哈尼族彝族傣族自治县", value: "yuanjianghanizuyizudai-zuzizhixian" },
      ],
    },
    {
      text: "保山市",
      value: "baoshan",
      children: [
        { text: "隆阳区", value: "longyang" },
        { text: "施甸县", value: "shidian" },
        { text: "龙陵县", value: "longling" },
        { text: "昌宁县", value: "changning" },
        { text: "腾冲市", value: "tengchong" },
      ],
    },
    {
      text: "昭通市",
      value: "zhaotong",
      children: [
        { text: "昭阳区", value: "zhaoyang" },
        { text: "鲁甸县", value: "ludian" },
        { text: "巧家县", value: "qiao-jia" },
        { text: "盐津县", value: "yanjin" },
        { text: "大关县", value: "daguan" },
        { text: "永善县", value: "yongshan" },
        { text: "绥江县", value: "suijiang" },
        { text: "镇雄县", value: "zhenxiong" },
        { text: "彝良县", value: "yiliang" },
        { text: "威信县", value: "weixin" },
        { text: "水富县", value: "shuifu" },
      ],
    },
    {
      text: "丽江市",
      value: "lijiang",
      children: [
        { text: "古城区", value: "gucheng" },
        { text: "玉龙纳西族自治县", value: "yulongnaxizuzizhixian" },
        { text: "永胜县", value: "yongsheng" },
        { text: "华坪县", value: "huaping" },
        { text: "宁蒗彝族自治县", value: "ninglangyizuzizhixian" },
      ],
    },
    {
      text: "普洱市",
      value: "puer",
      children: [
        { text: "思茅区", value: "simao" },
        { text: "宁洱哈尼族彝族自治县", value: "ningerhanizuyizuzizhixian" },
        { text: "墨江哈尼族自治县", value: "mojianghanizuzizhixian" },
        { text: "景东彝族自治县", value: "jingdongyizuzizhixian" },
        { text: "景谷傣族彝族自治县", value: "jinggudaiyizuzizhixian" },
        { text: "镇沅彝族哈尼族拉祜族自治县", value: "zhenyuan-yizuhani-zulahu-zuzizhixian" },
        { text: "江城哈尼族彝族自治县", value: "jiangchenghanizuyizuzizhixian" },
        { text: "孟连傣族拉祜族佤族自治县", value: "mengliandai-lahu-zuwa-zuzizhixian" },
        { text: "澜沧拉祜族自治县", value: "lanzhanglahuzuzizhixian" },
        { text: "西盟佤族自治县", value: "ximengwazuzizhixian" },
      ],
    },
    {
      text: "临沧市",
      value: "lincang",
      children: [
        { text: "临翔区", value: "linxiang" },
        { text: "凤庆县", value: "fengqing" },
        { text: "云县", value: "yunxian" },
        { text: "永德县", value: "yongde" },
        { text: "镇康县", value: "zhengkang" },
        { text: "双江拉祜族佤族布朗族傣族自治县", value: "shuangjianglahuzuwabulangzudai-zuzizhixian" },
        { text: "耿马傣族佤族自治县", value: "gengmadaiwazuzizhixian" },
        { text: "沧源佤族自治县", value: "cangyuanwazuzizhixian" },
      ],
    },
    {
      text: "楚雄州",
      value: "chuxiongyizuzizhizhou",
      children: [
        { text: "楚雄市", value: "chuxiong" },
        { text: "双柏县", value: "shuangbo" },
        { text: "牟定县", value: "mouding" },
        { text: "南华县", value: "nanhua" },
        { text: "姚安县", value: "yaoan" },
        { text: "大姚县", value: "dayao" },
        { text: "永仁县", value: "yongren" },
        { text: "元谋县", value: "yuanmo" },
        { text: "武定县", value: "wuding" },
        { text: "禄丰县", value: "lufeng" },
      ],
    },
    {
      text: "红河州",
      value: "hongheyizuzizhizhou",
      children: [
        { text: "个旧市", value: "gejiu" },
        { text: "开远市", value: "kaiyuan" },
        { text: "蒙自市", value: "mengzi" },
        { text: "弥勒市", value: "mile" },
        { text: "屏边苗族自治县", value: "pingbianmiaozuzizhixian" },
        { text: "建水县", value: "jianshui" },
        { text: "石屏县", value: "shiping" },
        { text: "泸西县", value: "luxi" },
        { text: "元阳县", value: "yuanyang" },
        { text: "红河县", value: "honghe" },
        { text: "金平苗族瑶族傣族自治县", value: "jinpingmiaoyuzudai-zuzizhixian" },
        { text: "绿春县", value: "lvchun" },
        { text: "河口瑶族自治县", value: "hekouyaotuzizhixian" },
      ],
    },
    {
      text: "文山州",
      value: "wenshanguizumiaozuzizhizhou",
      children: [
        { text: "文山市", value: "wenshan" },
        { text: "砚山县", value: "yan-shan" },
        { text: "西畴县", value: "xichou" },
        { text: "麻栗坡县", value: "malipo" },
        { text: "马关县", value: "maguan" },
        { text: "丘北县", value: "qiubei" },
        { text: "广南县", value: "guannan" },
        { text: "富宁县", value: "funing" },
      ],
    },
    {
      text: "西双版纳",
      value: "xishuangbanna-taizuzizhizhou",
      children: [
        { text: "景洪市", value: "jinghong" },
        { text: "勐海县", value: "menghai" },
        { text: "勐腊县", value: "menglai" },
      ],
    },
    {
      text: "大理州",
      value: "dali-baizuzizhizhou",
      children: [
        { text: "大理市", value: "dali" },
        { text: "漾濞彝族自治县", value: "yangbiyizuzizhixian" },
        { text: "祥云县", value: "xiangyun" },
        { text: "宾川县", value: "binchuan" },
        { text: "弥渡县", value: "midu" },
        { text: "南涧彝族自治县", value: "nanjianyizuzizhixian" },
        { text: "巍山彝族回族自治县", value: "weishanyizuhui-zuzizhixian" },
        { text: "永平县", value: "yongping" },
        { text: "云龙县", value: "yunlong" },
        { text: "洱源县", value: "eryuan" },
        { text: "剑川县", value: "jianchuan" },
        { text: "鹤庆县", value: "heqing" },
      ],
    },
    {
      text: "德宏州",
      value: "dehong-daizujingpozuzizhizhou",
      children: [
        { text: "瑞丽市", value: "ruili" },
        { text: "芒市", value: "mangshi" },
        { text: "梁河县", value: "lianghe" },
        { text: "盈江县", value: "yingjiang" },
        { text: "陇川县", value: "longchuan" },
      ],
    },
    {
      text: "怒江州",
      value: "nujianglisuzuzizhizhou",
      children: [
        { text: "泸水市", value: "lushui" },
        { text: "福贡县", value: "fugong" },
        { text: "贡山独龙族怒族自治县", value: "gongshandulongzunu-zuzizhixian" },
        { text: "兰坪白族普米族自治县", value: "lanpingbaizupumizuzizhixian" },
      ],
    },
    {
      text: "迪庆州",
      value: "diqingzangzuzizhizhou",
      children: [
        { text: "香格里拉市", value: "shangrilashi" },
        { text: "德钦县", value: "deqin" },
        { text: "维西傈僳族自治县", value: "weixilisuzuzizhixian" },
      ],
    },
  ];
  